collision_model_parameters:
  padding: 0.01
  links_with_padding: []
  blacklist:
    default:
      - first: ground_plane
        second: base_link
      - first: ground_plane
        second: caster_left_link
      - first: ground_plane
        second: caster_right_link
      - first: ground_plane
        second: wheel_right_link
      - first: ground_plane
        second: wheel_left_link
