arm_right_controller:
  ros__parameters:
    joints:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 5.0
      arm_right_1_joint:
        goal: 0.02
      arm_right_2_joint:
        goal: 0.02
      arm_right_3_joint:
        goal: 0.02
      arm_right_4_joint:
        goal: 0.02
      arm_right_5_joint:
        goal: 0.02
