arm_left_current_limit_controller:
  type: "pal_ros_controllers/CurrentLimitController"
  actuators:
    - arm_left_1_motor
    - arm_left_2_motor
    - arm_left_3_motor
    - arm_left_4_motor

arm_right_current_limit_controller:
  type: "pal_ros_controllers/CurrentLimitController"
  actuators:
    - arm_right_1_motor
    - arm_right_2_motor
    - arm_right_3_motor
    - arm_right_4_motor

wheels_current_limit_controller:
  type: "pal_ros_controllers/CurrentLimitController"
  actuators:
    - wheel_left_motor
    - wheel_right_motor
