hand_left_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - hand_left_fingers_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

    open_loop_control: true

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 5.0

hand_right_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - hand_right_fingers_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

    open_loop_control: true
    
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 5.0