joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    update_rate: 50
    extra_joints: 
      - 'caster_left_joint'
      - 'caster_right_joint'
      - 'hand_left_virtual_1_joint'
      - 'hand_left_virtual_2_joint'
      - 'hand_right_virtual_1_joint'
      - 'hand_right_virtual_2_joint'
