mobile_base_controller:
  ros__parameters:
    use_stamped_vel: False
    left_wheel_names  : ['wheel_left_joint']
    right_wheel_names : ['wheel_right_joint']
    #wheels_per_side: 1

    # In ROS1 these physical properties were parsed from the URDF
    wheel_radius: 0.0985
    wheel_separation: 0.4044

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # The params below were used in ROS1 but not yet in ROS2
    
    publish_rate: 50.0

    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    enable_pose_covariance_update: true
    error_constant_left : 0.001
    error_constant_right: 0.001
    # Velocity commands timeout [s]
    cmd_vel_timeout: 0.25
  
    # Base frame_id
    base_frame_id: base_footprint
  
    # Preserve turning radius when limiting speed/acceleration/jerk
    preserve_turning_radius: true
  
    # TODO: commented out while porting to ROS2 -> check if needs to be uncommented
    # # odom tf will be published by direct laser odometry
    # enable_odom_tf: false

    # Publish actual velocity cmd
    publish_cmd: true
    # Publish wheel data
    publish_wheel_data: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           :  1.0 # m/s
        min_velocity           : -0.2 # m/s
        has_acceleration_limits: true
        max_acceleration       :  1.0 # m/s^2
        has_jerk_limits        : false
        max_jerk               :  5.0 # m/s^3
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 2.09 # 120.0ยบ
        has_acceleration_limits: true
        max_acceleration       : 2.09 # 120.0ยบ
        has_jerk_limits        : false
        max_jerk               : 10.47 # 600.0ยบ

