play_motion2:
  ros__parameters:
    motion_planner:
      disable_motion_planning: false
      planning_groups: # Sorted by order of preference
        - both_arms
        - arm_left
        - arm_right
      exclude_from_planning_joints:
        - head_1_joint
        - head_2_joint
        - hand_left_fingers_joint
        - hand_right_fingers_joint
      joint_tolerance: 0.01

      # Parameters for non-planned approach
      approach_velocity: 0.5
      approach_min_duration: 0.5
