<?xml version="1.0"?>

<!--
  Copyright (c) 2019, PAL Robotics, S.L.
  All rights reserved.

  This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to
  Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find ari_description)/urdf/wheels/caster.gazebo.xacro"/>

  <xacro:macro name="caster" params="side reflect radius width separation_x offset_y offset_z parent">
    <link name="caster_${side}_link">
      <inertial>
        <origin xyz="${-0.016512 * reflect} 0.17601 ${-0.029897 * reflect}" rpy="0 0 0"/>
        <mass value="0.046595"/>
        <inertia  ixx="7.5074E-06" ixy="${-5.6754E-07 * reflect}" ixz="-2.3436E-07"
                  iyy="1.6751E-05" iyz="${-1.435E-08 * reflect}"
                  izz="1.1856E-05"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://ari_description/meshes/wheels/caster_v2.stl" scale="1 ${reflect} 1"/>
        </geometry>
        <material name="Grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://ari_description/meshes/wheels/caster_v2.stl" scale="1 ${reflect} 1"/>
        </geometry>
      </collision>
    </link>

    <joint name="caster_${side}_joint" type="continuous">
      <parent link="${parent}_link"/>
      <child link="caster_${side}_link"/>
      <origin xyz="${-separation_x / 2} ${-offset_y * reflect} ${offset_z}" rpy="${0.0 * deg_to_rad} 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <!-- Gazebo extensions -->
    <xacro:caster_gazebo side="${side}"/>

  </xacro:macro>
</robot>

