<?xml version="1.0"?>

<!--
  Copyright (c) 2019, PAL Robotics, S.L.
  All rights reserved.

  This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to
  Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
-->

    <!--  CHECK PARAMETERS FROM BASE_V2 FILE -->


<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find ari_description)/urdf/wheels/caster.gazebo.xacro"/>

  <xacro:macro name="caster" params="side reflect radius width separation_x offset_y offset_z parent">
    <link name="caster_${side}_link">
      <inertial>
        <origin xyz="${1.4445E-06 * reflect} 0.016213 ${-0.00019766 * reflect}" rpy="0 0 0"/>
        <mass value="0.24242"/>
        <inertia  ixx="0.0002099" ixy="${-5.5806E-09 * reflect}" ixz="-6.9375E-11"
                  iyy="0.00020239" iyz="${-2.6771E-09 * reflect}"
                  izz="0.00025496"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://ari_description/meshes/wheels/caster_${side}.stl"/>
        </geometry>
        <material name="Grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${width}"/>
        </geometry>
      </collision>
    </link>

    <joint name="caster_${side}_joint" type="continuous">
      <parent link="${parent}_link"/>
      <child link="caster_${side}_link"/>
      <origin xyz="${-separation_x / 2} ${-offset_y * reflect} ${offset_z}" rpy="${90.0 * deg_to_rad} 0 0"/>
      <axis xyz="0 0 -1"/>
    </joint>

    <!-- Gazebo extensions -->
    <xacro:caster_gazebo side="${side}"/>

  </xacro:macro>
</robot>

