<?xml version="1.0"?>

<!--
Copyright (c) 2019, PAL Robotics, S.L.
All rights reserved.

This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to
Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find ari_description)/urdf/wheels/wheel.transmission.xacro"/>
  <xacro:include filename="$(find ari_description)/urdf/wheels/wheel.gazebo.xacro"/>

  <xacro:macro name="wheel" params="side reflect radius width torque velocity separation parent">
    <link name="wheel_${side}_link">
    <inertial>
      <origin xyz="-6.7466E-06 0.00019427 -1.3878E-17" rpy="0 0 0"/>
      <mass value="2.0456" />
      <inertia ixx="0.0052532" ixy="-2.566E-08" ixz="${1.1121E-18 * reflect}"
               iyy="0.009772" iyz="${2.3459E-17 * reflect}"
               izz="0.0052531" />
    </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="${-90 * deg_to_rad}  0 0"/>
        <geometry>
          <mesh filename="package://ari_description/meshes/wheels/wheel_${side}_v2.stl"/>
        </geometry>
        <material name="White"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${width}"/>
        </geometry>
      </collision>
      <kinematic>0</kinematic>
      <gravity>1</gravity>
    </link>    

    <joint name="wheel_${side}_joint" type="continuous">
      <parent link="${parent}_link"/>
      <child link="wheel_${side}_link"/>
      <origin xyz="0 ${ -separation / 2 * reflect} 0" rpy="${90 * deg_to_rad} 0 0"/>
      <axis xyz="0 0 -1"/>
      <limit effort="${torque}" velocity="${velocity / radius}"/>
    </joint>

    <!-- Transmission -->
    <xacro:wheel_transmission side="${side}"/>

    <!-- Gazebo extensions -->
    <xacro:wheel_gazebo side="${side}"/>

  </xacro:macro>
</robot>
