<?xml version="1.0"?>
<!--
  Copyright (c) 2023 PAL Robotics S.L. All rights reserved.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 -->

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find ari_description)/ros2_control/transmissions.urdf.xacro"/>

  <xacro:macro name="wheel" params="side reflect radius width torque velocity separation parent">
    <link name="wheel_${side}_link">
      <inertial>
        <origin xyz="-5.88525464208667E-06 -7.00561297658359E-05 ${-0.00222902971508132 * reflect}" rpy="0 0 0"/>
        <mass value="1.65651"/>
        <inertia ixx="0.00630296404438488" ixy="1.03273612245952E-10" ixz="${-7.08413602420107E-07 * reflect}"
                 iyy="0.00630218683572781" iyz="${-5.36273874221441E-08 * reflect}"
                 izz="0.0111537170515009"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://ari_description/meshes/wheels/wheel_${side}.stl"/>
        </geometry>
        <material name="White"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${width}"/>
        </geometry>
      </collision>
      <kinematic>0</kinematic>
      <gravity>1</gravity>
    </link>    

    <joint name="wheel_${side}_joint" type="continuous">
      <parent link="${parent}_link"/>
      <child link="wheel_${side}_link"/>
      <origin xyz="0 ${-separation / 2 * reflect} 0" rpy="${90.0 * deg_to_rad} 0 0"/>
      <axis xyz="0 0 -1"/>
      <limit effort="${torque}" velocity="${velocity / radius}"/>
    </joint>

    <!-- Transmission -->
    <xacro:ari_simple_transmission name="wheel_${side}"/>

  </xacro:macro>
</robot>
